#!/usr/bin/env perl

use common::sense;
use Digest::MD5 qw(md5_hex);
use File::Find;  #not needed yet, later for recursion
use Getopt::Std; #not needed yet, later for other path than working directory

# TODO: option -r (recursive); parameter DIR (if different from actual directory).

my @files=glob'*';
my %filehashes;

foreach my $file(@files) {
  if (-d $file or -l $file) {
	  next;
	}
	open FILE, "< $file";
	my $digest=md5_hex(<FILE>);
	if (exists $filehashes{$digest}) {
	  push @{$filehashes{$digest}}, $file;
    print "duplicates detected: ";
    foreach $file (@{$filehashes{$digest}}) {
			print "$file   ";
    }
	print "\n";	
	next;
	}	
	$filehashes{$digest}=[$file];
}

exit 0;

# sollte der -r switch doch noch dazukommen, können die dateinamen gleich sein, aber in
# verschieden pfaden stehen - kein problem, kompletten pfad mit namen speichern.
#
# als aufrufparameter könnte auch ein anderes als das aktuelle verzeichnis eingegeben werden.
