#!/usr//bin/env perl

use Config;
use strict;
use warnings;

my $separator = $Config{path_sep};
my $pattern = shift(@ARGV) or die "Usage: rhich PATTERN - The search pattern is mandatory.\n";
my @pfade = split /$separator/, $ENV{"PATH"};

foreach my $pfad (@pfade) {
	if (-e $pfad) {
		chdir $pfad;
		my @files=glob"$pattern*";
		foreach my $file (@files) {
			if (-x $file) {
				print "$file is in $pfad\n";
			}
		}
	}
}

exit 0

# vim: sw=4
